Edits for Octa (70014)
Giratena/Succubus-Duel-English-Translation pull request #148
Opened 2024-08-19 23:33 UTC by HotHeadEmperor

2024-08-20 12:27 UTC, Giratena requested changes
Just spotted some more things @HotHeadEmperor @Kyrari ^^

There may be more, but I'll let you know if I spot more things.

2024-08-20 12:27 UTC, Giratena commented on CSV/Language/English/Card/70014.txt
> +男のマスターでサキュバスに勝つって相当なものよ。\nたとえＣランクのマスターでも、\n男ならたいてい下級サキュバスにすら勝てないわ。,Male cardmasters beating a succubus is quite the feat. Even for a male C-rank cardmaster; most of them can't win against a low-rank
Even a male C-rank cardmaster would struggle to win against a low-rank succubus.

2024-08-20 12:27 UTC, Giratena commented on CSV/Language/English/Card/70014.txt
> +サキュバスとの戦い大変だったわよね？\nぬるぬるの体で何度も扱かれて、\nでもサキュバス相手じゃ、射精するわけにもいかない…❤,Fighting succubi must be tough; isn't it? They'll use their slimy bodies on you again and again; but you can't ejaculate on them...❤
Fighting succubi is tough; isn't it?

; but you can never let them make you ejaculate...❤

2024-08-20 12:27 UTC, Giratena commented on CSV/Language/English/Card/70014.txt
>  そのまま扱くだけでも気持ちいいのに、\nローションでぬるぬるの指が、\nあなたの亀頭をわしゃわしゃ…❤ぐちゅぐちゅ…❤,Just stroking it would feel good already; but my fingers will be coated in lotion and stroking your glans...❤ Squish; squish...❤
Just stroking it like this would already feel good; but with my fingers coated in lotion and stroking your glans as well...❤

@Kyrari remember to translate そのまま!

2024-08-20 12:27 UTC, Giratena commented on CSV/Language/English/Card/70014.txt
> +ズボンの上からきれいな指がすぅーっとペニスをなでる。指先についたローションが、しっとりとしみこんで、ズボンがほんのりと濡れていく。,Her beautiful fingers smoothly caressed me over my pants. Her fingertips coated in lotion slowly soak into my pants; turning them wet
Her beautiful fingers smoothly caressed my dick from over my pants; slowly becoming wet from her lotion coated fingertips.

Sometimes it's better to be concise @Kyrari @HotHeadEmperor ^^

2024-08-20 12:27 UTC, Giratena commented on CSV/Language/English/Card/70014.txt
> +例えばこんな風に両足でぎゅってチンポを捕まえて、前後にしゅっしゅって動かすのはどう？足裏がぴったり吸い付いてきて気持ちいいでしょ❤,For example; what if I use both of my feet to grab your dick like this and move it back and forth? The soles of my feet sticking to y
"The soles of my feet sticking to your dick" is a pretty unnatural English sentence aha @Kyrari 

-> The soles of my feet fit perfectly around your dick; and it feels great; right?❤

2024-08-20 15:24 UTC, HotHeadEmperor commented on CSV/Language/English/Card/70014.txt
> +ローションが彼女の動きに合わせて微弱に上下に動いてくる！,The lotion is moving; gently following her movements!
Made a slight change here to avoid repetition of 'move' and help it flow.

2024-08-20 15:27 UTC, HotHeadEmperor commented on CSV/Language/English/Card/70014.txt
> +男のマスターでサキュバスに勝つって相当なものよ。\nたとえＣランクのマスターでも、\n男ならたいてい下級サキュバスにすら勝てないわ。,Male cardmasters beating a succubus is quite the feat. Even for a male C-rank cardmaster; most of them can't win against a low-rank
Made a slight change here, moving C-rank before male, since 'male cardmaster' is essentially a unified subject here, and C-rank is the changing qualifier.

2024-08-20 15:30 UTC, HotHeadEmperor commented on CSV/Language/English/Card/70014.txt
> +ズボンの上からきれいな指がすぅーっとペニスをなでる。指先についたローションが、しっとりとしみこんで、ズボンがほんのりと濡れていく。,Her beautiful fingers smoothly caressed me over my pants. Her fingertips coated in lotion slowly soak into my pants; turning them wet
Change accepted, just hyphenated where needed.

2024-08-20 15:31 UTC, HotHeadEmperor commented on CSV/Language/English/Card/70014.txt
> +例えばこんな風に両足でぎゅってチンポを捕まえて、前後にしゅっしゅって動かすのはどう？足裏がぴったり吸い付いてきて気持ちいいでしょ❤,For example; what if I use both of my feet to grab your dick like this and move it back and forth? The soles of my feet sticking to y
Mostly changed, though I feel 'doesn't it' still sounds better and fits with the other sentences better. If you disagree, just let me know.

2024-08-20 21:25 UTC, Giratena commented on CSV/Language/English/Card/70014.txt
> +例えばこんな風に両足でぎゅってチンポを捕まえて、前後にしゅっしゅって動かすのはどう？足裏がぴったり吸い付いてきて気持ちいいでしょ❤,For example; what if I use both of my feet to grab your dick like this and move it back and forth? The soles of my feet sticking to y
Nope that's okay too!

2024-08-25 06:45 UTC, Giratena requested changes
A very very good proofread! Made some more comments but overall a great job! Thanks a bunch @HotHeadEmperor :D

2024-08-25 06:45 UTC, Giratena commented on CSV/Language/English/Card/70014.txt
> +そう言って肩をすくめると、オクタと名乗ったカードマスターは僕の隣に腰かけた。,As she said that; the cardmaster Octa shrugged her shoulders and sat down next to me.
Hmm... I think "Cardmaster Octa" feels more natural. Even just "Octa" would be OK as the reader knows she's a card master at this point ^^

2024-08-25 06:45 UTC, Giratena commented on CSV/Language/English/Card/70014.txt
> +水属性キャラクターと戦闘するとき{使用カード}の効果を発動！ターン終了時まで自身の攻撃力を400ポイントアップするわ。,When attacking a Water Attribute enemy; activate {使用カード}'s effect! Until the turn ends; increase their attack power by 400 points.
-> enemy; _I_ activate

2024-08-25 06:45 UTC, Giratena commented on CSV/Language/English/Card/70014.txt
> +戦闘するとき{使用カード}の効果を発動！相手が水属性でない場合、そのモンスターを水属性に変化させるわ。,Activate {使用カード}'s effect during combat! If the target isn't a Water Attribute; change the targets's attribute into Water Attribute.
Simply "target's" is OK here ^^

2024-08-25 06:45 UTC, Giratena commented on CSV/Language/English/Card/70014.txt
> +戦闘時に{使用カード}の効果を発動！相手の属性を水属性に変化するわ。,Activate {使用カード}'s effect during combat! Change the targets's attribute into Water Attribute.
Target's

2024-08-25 06:45 UTC, Giratena commented on CSV/Language/English/Card/70014.txt
> +くす❤腰が震えてる❤もう出しちゃうんだ❤,*Giggle*❤ It's already trembling.❤ It's gonna shoot out so soon.❤
Hmm I think this might have been OK originally! "It's gonna shoot out already.❤" sounds more natural to me I think ^^

2024-08-25 06:45 UTC, Giratena commented on CSV/Language/English/Card/70014.txt
> +ほら、こうして挟んで上下にごしごし❤\n土踏まずの圧力が気持ちいいでしょ？ふふふ…❤,Look; I'll step on it and rub it up and down like this.❤ Doesn't it feel good to get pleasured by the arch of my foot? Hehe...❤
The translation here is "pressure". Maybe a reword such as "Doesn't feel good to have your dick pressed between the arches of my feet?"

2024-08-25 06:45 UTC, Giratena commented on CSV/Language/English/Card/70014.txt
> +敏感になった亀頭を、乱暴に足でごしごしごし❤\nあは、どんどん腰が浮いてきてる❤\n下級モンスターじゃ耐えられないかしら。くすくす❤,Now for your sensitive glans; I'll rub you roughly with my feet.❤ Ehe; your hips are starting to rise.❤ Is this too much for a low r
Good spots here by swapping out "this" for "your". Japanese often ommits this stuff so it's a good call to see it back here!

2024-08-25 06:45 UTC, Giratena commented on CSV/Language/English/Card/70014.txt
> +試合前にシコシコされてここまで我慢できたのにね❤\nでも結局寸止めされたのがずっとうずいてて、\n耐えられなくなっちゃったのよね❤,You've kept enduring since getting jerked before the match up until now~❤ But in the end; you couldn't bear the constant throbbing fr
Good simplification here.

2024-08-25 06:45 UTC, Giratena commented on CSV/Language/English/Card/70014.txt
> +マスターの大事な大事な初試合なのに、自分の快楽を優先して次から次に裏切りオナニー❤ルーキーくんに同情しちゃうわ❤,Even though it’s your master’s precious debut match; they chose their own pleasure and betray him one after another .❤ I’m starting to feel so
Hmm this sounds weird to me. Maybe "they gave in to their own desires and betrayed him"?

2024-08-25 15:37 UTC, HotHeadEmperor commented on CSV/Language/English/Card/70014.txt
> +戦闘するとき{使用カード}の効果を発動！相手が水属性でない場合、そのモンスターを水属性に変化させるわ。,Activate {使用カード}'s effect during combat! If the target isn't a Water Attribute; change the targets's attribute into Water Attribute.
I played with this one a little bit, because the repetition felt clunky. Let me know what you think.

2024-08-25 21:54 UTC, Giratena approved these changes

2024-08-25 21:54 UTC, merged