(WIP) Translate Burning Heat Shamaness (10029)
Giratena/Succubus-Duel-English-Translation pull request #163
Opened 2024-08-26 12:17 UTC by Giratena

2024-09-23 17:24 UTC, HotHeadEmperor commented on CSV/Language/English/Card/10029.txt
> +　炎を操る妖艶な巫女。儀式のために身に付けた踊りはどこかなまめかしく、見ているものの心を捕らえて魅了してしまう。まるで炎に誘われる羽虫のように彼女に近づけば、そのしなやかな脚や呪文を蠱惑的に紡ぐ口に翻弄され、そのまま精を搾り取られて儀式の供物にされてしまうだろう。,A bewitching Shrine Maiden with the power to control fire. The cer
spell-casting should be hyphenated here since its specifically describing her mouth I believe.

2024-09-23 17:24 UTC, HotHeadEmperor commented on CSV/Language/English/Card/10029.txt
> +この状態で先端をピストンしてあげれば、みんなイっちゃうのよ。\nほら、んっ❤んっ❤じゅるるぅ❤,In When I piston the tip this state; everyone ends up cumming! Hora; mmph- mmph-❤ *Succcck*~❤
'And when' or just 'When'

2024-09-23 17:24 UTC, HotHeadEmperor commented on CSV/Language/English/Card/10029.txt
> +くす❤この脚を絡みつけられたいの？\nわたしの高い体温でペニスを包まれて、\nどれだけ耐えられるのかしら❤,*Giggle*❤ So you want to writhe between my legs? I wonder how much your dick will be able to withstand against my warm body heat.❤
Maybe remove 'against' Something like 'I wonder how much your dick will be able to withstand the warm heat of my body.'

2024-09-28 12:43 UTC, Giratena commented on CSV/Language/English/Card/10029.txt
> +　炎を操る妖艶な巫女。儀式のために身に付けた踊りはどこかなまめかしく、見ているものの心を捕らえて魅了してしまう。まるで炎に誘われる羽虫のように彼女に近づけば、そのしなやかな脚や呪文を蠱惑的に紡ぐ口に翻弄され、そのまま精を搾り取られて儀式の供物にされてしまうだろう。,A bewitching Shrine Maiden with the power to control fire. The cer
Thank you!

2024-09-28 12:44 UTC, Giratena commented on CSV/Language/English/Card/10029.txt
> +この状態で先端をピストンしてあげれば、みんなイっちゃうのよ。\nほら、んっ❤んっ❤じゅるるぅ❤,In When I piston the tip this state; everyone ends up cumming! Hora; mmph- mmph-❤ *Succcck*~❤
Good spot

2024-09-28 12:45 UTC, Giratena commented on CSV/Language/English/Card/10029.txt
> +くす❤この脚を絡みつけられたいの？\nわたしの高い体温でペニスを包まれて、\nどれだけ耐えられるのかしら❤,*Giggle*❤ So you want to writhe between my legs? I wonder how much your dick will be able to withstand against my warm body heat.❤
Reworded thank you ^^

2024-10-01 03:31 UTC, Erbstin commented
Shamaness has an extra effect on hard. If she dies to combat damage, she summons a Lava Girl
![image](https://github.com/user-attachments/assets/42ae32be-1168-4f1b-bcc4-d58ec5d04b5a)

2024-10-01 06:26 UTC, Erbstin requested changes
Review of the fire shamaness dialogue. Take these purely as suggestions and opinions. You've written good stuff!

2024-10-01 06:26 UTC, Erbstin commented on CSV/Language/English/Card/10029.txt
> +そんなに気持ちがいい事を味わなくて後悔するんじゃないかしら？,If you don't expereince the feeling of this wonderful thing I can do; you'll surely regret it right?
`expereince` => `experience`

also trying to think of a way to replace "thing I can do"

Perhaps:
> If you don't experience my wonderful offer; you'll surely regret it; right?

2024-10-01 06:26 UTC, Erbstin commented on CSV/Language/English/Card/10029.txt
> +このまま抱きしめて、お腹でイかせてあげてもいいけれど\nふとももで挟んであげるって言ったから、挟んであげるわね❤,I would keep you like this until you leaked onto my stomach... but I said I'd rub yoru dick between my thighs; so that's exactly what I'll do.
`yoru` => `your`

2024-10-01 06:26 UTC, Erbstin commented on CSV/Language/English/Card/10029.txt
> +チンポの先端をふとももの谷間に合わせてっと❤\nゆっくりいれるから楽しんでね❤,I'll slip the tip of your dick just between my thighs...❤ I'll do it real slowly so you can enjoy it; OK?❤
maybe this instead? `I'll do it bit by bit so you can enjoy it; OK?❤`

2024-10-01 06:26 UTC, Erbstin commented on CSV/Language/English/Card/10029.txt
> +それじゃあ、踊りで鍛えた腰ふりでイかせてあげる❤,Now then; time to sway my hips to my sultery dance and make you cum~❤
`sultery` => `sultry`

2024-10-01 06:26 UTC, Erbstin commented on CSV/Language/English/Card/10029.txt
> +太ももで先端から根元までゴシゴシ擦られて、\nセックスしているみたいに気持ちいいでしょう？,Having my thighs rub your dick rubbed from the base to tip like this feels just like sex; right?
Could use a little rewording:
> Having my thighs rub your dick from base to tip like this feels just like sex; right?

2024-10-01 06:26 UTC, Erbstin commented on CSV/Language/English/Card/10029.txt
> +ここに出しても子供はできないけれど、その分快感は約束するわ❤\n思いっきり踊ってあげるから、思いっきりイって❤,You won't be able to make a baby like this; but trust me; the pleasure it brings will blow your mind~❤ I'll dance my heart out; so you cum you
missing "r" in your:
`you cum you heart out too~❤` should be `you cum your heart out too~❤`

2024-10-01 06:26 UTC, Erbstin commented on CSV/Language/English/Card/10029.txt
> +女の脚に負けちゃったわね❤脚なんかで喘がされて、マゾってみじめ❤\nくすくす❤,You really went and lost to a woman's legs huh.❤ It's sad when Masocists are made to moan with something as lame as their legs.❤ *Giggle*❤
`Masocists` => `masochists`

2024-10-01 06:26 UTC, Erbstin commented on CSV/Language/English/Card/10029.txt
> +炎熱の巫女のフェラはどうだった？あっつあつの口内でチンポ溶かされちゃったんじゃない？,How did you like getting blowjob from a flame shamaness? I bet it felt like your dick was melting in my wet hot mouth right?
should be "getting a blowjob"

2024-10-01 06:26 UTC, Erbstin commented on CSV/Language/English/Card/10029.txt
> +ふふ、ビクンって体ごと反応しちゃった❤\nあなたのチンポも、あなたの表情も…、\n「もっと搾ってぇ」っておねだりしているように見えるわ❤,Your body; your facial expression; your...cock~ They're all telling me how badly you need to be milked.❤
`your facial expression;` => `your face;`

2024-10-01 06:26 UTC, Erbstin commented on CSV/Language/English/Card/10029.txt
> +あつあつの口内で舌がチンポに絡みついて…❤\n溶けちゃいそうでしょう？下手な女の子との本番エッチより、\nずっと気持ちいいの❤,When my tounge is swirling around your dick inside my hot mouth like this... it feels like it's going to melt right?❤ I bet it feels so
`tounge` => `tongue`

2024-10-01 06:26 UTC, Erbstin commented on CSV/Language/English/Card/10029.txt
> +顔がベールで隠れているせいで、彼女の口の動きがあいまいにしか見えない。カリ首に舌を絡められたり、急に唇で竿に吸い付かれたり、予想できない快楽が僕を襲ってくる。,With her face hidden behind her veil; it was hard to see the exact movements of her mouth. Sometimes she would flick he
`assulting` => `assaulting`

2024-10-01 06:26 UTC, Erbstin commented on CSV/Language/English/Card/10029.txt
> +ちゅぷ❤える❤ぷちゅ❤\nとっても敏感で、かわいいチンポ❤\nまだ少ししか経っていないのにもう限界なのね。,*Suck*❤ *Suck*❤ *Mwah*❤ You've got such a lovely; sensitive dick.❤ It hasn't been that long and you're already reached your limit.
either `you're already at your limit.` or `you've already reached your limit.`

2024-10-01 06:26 UTC, Erbstin commented on CSV/Language/English/Card/10029.txt
> +頭を前後に動かして、激しくフェラしてあげる❤\nガチガチチンポなら腰が抜けちゃうぐらい気持ちよくなるわよ❤,I'll move my head back and forth and give you a intense blowjob.❤ It'll make you feel so good that your lower body will give in and lose all stre
"a" should be "an":
> an intense blowjob

2024-10-02 16:01 UTC, HotHeadEmperor commented on CSV/Language/English/Card/10029.txt
> +んっ❤おいしい❤\n口の中にたくさん出して、それを飲んでもらえて、満足かしら？\n変態さん❤,Mm~❤ Delicious!❤ Hey pervert! Does satisfy you when I drink your sperm after you've shot your load into my mouth?❤
Personally I don't care for the use of the word 'down.' It feels out of character from her other lines. A little more casual.

2024-10-02 16:03 UTC, HotHeadEmperor commented on CSV/Language/English/Card/10029.txt
> +くす❤女の脚にあっという間に屈服しちゃったわね❤\nチンポいじめてもらえてうれしかったでしょ？\n変態さん❤,*Giggle*❤ I've never seen someone surrender so quickly to my legs.❤ Did you enjoy having your dick teased: pervert?❤
Or it could be separate. "Did you enjoy having your dick teased? Pervert." Might flow a little nicer.

2024-10-02 16:04 UTC, HotHeadEmperor commented on CSV/Language/English/Card/10029.txt
> +ほら見て、ベールの隙間から私の舌が見えるでしょう❤\n炎みたいに真っ赤な色の舌…❤\nれろぉーっていやらしく動かしてあげる❤,Hora. Look my tongue through the veil covering my mouth; burning red like the heat of my flames...❤ I'll give you a demonstration my lew
I left it as is in mine because I feel like its more of a command. Sort of a "watch me" idea.

2024-10-02 16:11 UTC, HotHeadEmperor commented on CSV/Language/English/Card/10029.txt
> +あら、敵モンスターであるわたしに\n「もっと攻撃して」ってお願いしちゃうの？\nくすくす❤マゾなのね、あなた❤,Oh? Are you asking me; an enemy monster; to keep attacking you? *Giggle*❤ You're a real masocist.❤
Really good eye on this one. I missed all three.

2024-10-02 20:18 UTC, Erbstin commented on CSV/Language/English/Card/10029.txt
> +くす❤女の脚にあっという間に屈服しちゃったわね❤\nチンポいじめてもらえてうれしかったでしょ？\n変態さん❤,*Giggle*❤ I've never seen someone surrender so quickly to my legs.❤ Did you enjoy having your dick teased: pervert?❤
Ooo I do like that a lot better

2024-10-02 20:32 UTC, Erbstin commented on CSV/Language/English/Card/10029.txt
> +ほら見て、ベールの隙間から私の舌が見えるでしょう❤\n炎みたいに真っ赤な色の舌…❤\nれろぉーっていやらしく動かしてあげる❤,Hora. Look my tongue through the veil covering my mouth; burning red like the heat of my flames...❤ I'll give you a demonstration my lew
It definitely is more of a command. 見て pretty much conclusively affirms that.

I'm good with "Look at my tongue"

I still think it should go without "covering my mouth" though. What other veil would there be?

2024-10-02 20:35 UTC, Erbstin commented on CSV/Language/English/Card/10029.txt
> +踊りで鍛えたむちむちの脚❤\nそれをチンポに巻き付けて、ダンスでも踊るみたいに\n前後に、にゅこにゅこにゅこ…❤,These thick legs of mine are made for dancing.❤ I'll wrap them around your dick and give you a little dance number swinging my hips back and f
I'd never heard of a dance number, but that's totally a thing.  Disregard/Resolve this.

2024-10-04 03:11 UTC, Giratena commented on CSV/Language/English/Card/10029.txt
> +わたしの体あたたかいから、\nふとももに挟んであげるだけなのに\nセックスしているのと勘違いしちゃう人もいるのよ。,It may not seem like much but because my body is so warm; some people are tricked into believing they're having sex with me!
I really like this I'll use that ^^

2024-10-04 03:12 UTC, Giratena commented on CSV/Language/English/Card/10029.txt
> +わたしの体あたたかいから、\nふとももに挟んであげるだけなのに\nセックスしているのと勘違いしちゃう人もいるのよ。,It may not seem like much but because my body is so warm; some people are tricked into believing they're having sex with me!
Changed to: 
Because my body is so warm; some people are tricked into believing they're having sex with me; even though I've only put their dick between my thighs!

To keep the meaning - don't wanna drop off the word thighs here.

2024-10-04 03:15 UTC, Giratena commented on CSV/Language/English/Card/10029.txt
> +あら、敵にエナジーを貢いでおいてそんな蕩けた顔しちゃダメよ❤\n濃厚なエナジーで傷もなにかも元通り❤\nあなたのせいで他の仲間がピンチね。くすくす❤,Ara; it's not good to look so pleased with yourself after supplying your enemy with mana; which will heal my wounds and othe
This is a really good spot!

2024-10-04 03:17 UTC, Giratena commented
Thank you very much for your proofreading @Erbstin! I've made your fixes and will merge this in now ^^

2024-10-04 03:17 UTC, merged

2024-10-05 04:03 UTC, Erbstin commented
@Giratena I think the comments that got hidden were missed. Let's at least get the `expereince` typo on line 91

To see the hidden comments:
![image](https://github.com/user-attachments/assets/a9ee6154-a615-4895-a680-3cc62c28354d)