Feat: Add translation for Event/GuildTutorial.txt
Giratena/Succubus-Duel-English-Translation pull request #167
Opened 2024-09-04 20:56 UTC by Noitcereon

## Changes
- Added a machine translated GuildTutorial.txt with some minor corrections.

2024-09-04 22:33 UTC, Giratena commented
Ooh thank you for your PR @Noitcereon!

The translation is a bit Engrishy, but since this is quite a short file I should be able to go through at some point with better translations to show you what I mean when I get around to reviewing this.

2024-09-04 22:35 UTC, Giratena commented
I've also edited your pr title to (Ready) for you as this is what we are using to show PRs that need to be looked at ^^

2024-09-05 13:56 UTC, Noitcereon commented
I tried to make it less "Engrishy" (make it feel more like natively spoken English). Hopefully it's better.

2024-09-05 18:45 UTC, HotHeadEmperor reviewed
Wanted to take a stab at a few quick corrections and recommendations.

2024-09-05 18:45 UTC, HotHeadEmperor commented on CSV/Language/English/Event/GuildTutorial.txt
> +スライムのサキュバスを倒した次の日。僕は師匠に言われた通りカードマスターギルドの建物を訪ねていた。,The day after I defeated the slime succubus; I went to the Card Master Guild building as my master had told me to.
Hey man, just a heads up, for all instances in this translation, 'Cardmaster' or 'cardmaster' is always one word.

2024-09-05 18:45 UTC, HotHeadEmperor commented on CSV/Language/English/Event/GuildTutorial.txt
> +あら、見ない顔ですね。新規の登録者さんですか？,Oh; I don't recognize you. Are you a new card master?
'cardmaster'

2024-09-05 18:45 UTC, HotHeadEmperor commented on CSV/Language/English/Event/GuildTutorial.txt
> +あいにくギルドマスターのリーフは外出中ですが、\n言伝を受けております。,Unfortunately; Guild Master Leif is out, but\n he has been informed.
maybe change 'been informed' to 'received word' to help connect the fact that they got a note or letter.

2024-09-05 18:45 UTC, HotHeadEmperor commented on CSV/Language/English/Event/GuildTutorial.txt
> +今回は守護者資格のあるカードマスターからの推薦ですので、\n入会審査はなしで大丈夫です。,Since you have a recommendation from a card master who has guardian qualifications; there is no need for an entrance examination.
'cardmaster'

2024-09-05 18:45 UTC, HotHeadEmperor commented on CSV/Language/English/Event/GuildTutorial.txt
> +えーと、お名前は{主人公}さん……、\nふむふむ、出身はだいぶ北にある村なんですね。,Umm; so your name is {主人公}... \n I see; you're from a village quite far to the north.
Might flow better if you change it to 'I see. You're' with a period

2024-09-05 18:45 UTC, HotHeadEmperor commented on CSV/Language/English/Event/GuildTutorial.txt
> +登録おつかれさまです。\n新人カードマスターはまずはFランクからのスタートです。,Thank you for registering. \n New Card Masters will start out at F rank.
'cardmaster' here should be lowercase

2024-09-05 18:45 UTC, HotHeadEmperor commented on CSV/Language/English/Event/GuildTutorial.txt
> +はい。ギルドのカードマスターにはランクがあり、\n上からA、B、C、D、E、Fと6段階あります。,Yes. Guild card masters have ranks; with six levels: A; B; C; D; E; and F from the top.
'cardmaster.' Might sound better if you add 'top to bottom.'

2024-09-05 18:45 UTC, HotHeadEmperor commented on CSV/Language/English/Event/GuildTutorial.txt
> +例えば、あなたの師匠であるコノハさんは\nB級のカードマスターですね。B級ともなると\n「守護者」として地域の治安維持を任されることもあります。,For example; your master; Konoha; is a B-rank card master. B-rank card masters are sometimes entrusted with maintaining peace
'cardmaster'

2024-09-05 18:45 UTC, HotHeadEmperor commented on CSV/Language/English/Event/GuildTutorial.txt
> +大会の最中は他のカードマスターに勝つことで、\nどんどん自分のランクをあげていくことができるんですよ。,During the tournament; you can steadily increase your rank by defeating other card masters.
'cardmaster'

2024-09-05 18:45 UTC, HotHeadEmperor commented on CSV/Language/English/Event/GuildTutorial.txt
> +F級から一気にA級まで行った人はわたしの知る限りではいませんが…\nもしかしたらあなたならできるかもしれません。頑張ってくださいね！,As far as I know; no one has gone from F-class to A-class in one go... but maybe you can do it. Good luck!
Maybe change 'class' to 'rank' for consistency

2024-09-05 18:45 UTC, HotHeadEmperor commented on CSV/Language/English/Event/GuildTutorial.txt
> +B級やA級になるためにはふつう何年もかかりますが、\nうまく勝ち抜ければこの大会中にA級になることだって夢ではありません。,It usually takes years to reach B or A rank; but if you win your battles; it's not a dream to reach A rank during this tournament.
Maybe 'fantasy' instead of 'dream,' or just something like 'it's not impossible.'

2024-09-07 13:27 UTC, Noitcereon commented
Force pushed to fix minor mistake in previous commit.

2024-09-15 07:43 UTC, Giratena requested changes
Much much better! Nice work @HotHeadEmperor for proofreading it and shaping it up and @Noitcereon being so quick on the changes.

Two comments from me. Once they are done I'll merge ^^

2024-09-15 07:43 UTC, Giratena commented on CSV/Language/English/Event/GuildTutorial.txt
> +「南の村の守護者コノハが、\n若いけれど優秀な弟子をギルドに向かわせる」\nとのことでしたが…。,"Konoha; the protector of the southern village; will be sending a young but talented apprentice to the guild;" it said.
"It said" is a little unnatural for English! Maybe...

She was told; "Konoha; the protector of the southern village; will be sending a young but talented apprentice to the guild."

2024-09-15 07:43 UTC, Giratena commented on CSV/Language/English/Event/GuildTutorial.txt
> +えーと、お名前は{主人公}さん……、\nふむふむ、出身はだいぶ北にある村なんですね。,Umm; so your name is {主人公}... \n I see. You're from a village quite far to the north.
Umm -> Let's see. So your name is

Also we aren't included /n in the translation (with some exceptions). So feel free to remove them ^^

2024-09-15 09:50 UTC, Giratena approved these changes
Nicely done! I will approve and merge this in ^^

2024-09-15 09:50 UTC, merged