(READY) Gemini's reward (70024)
Giratena/Succubus-Duel-English-Translation pull request #172
Opened 2024-09-25 15:21 UTC by PummelsTL

Gemini Event.

2024-10-04 23:43 UTC, Giratena requested changes
Just some flow and translation changes from me! I think these will make it better too ^^

2024-10-04 23:43 UTC, Giratena commented on CSV/Language/English/Card/70024.txt
> +お姉さんが手を引いて連れて行ってあげるね❤\n控え室でたくさん気持ちいい「お礼」をしてあげる～❤,Now; why don't you take big sis' hand? I'll take you to an empty room and give you a "reward" that makes you feel good.❤
"Now; why don't you take big sis' hand?" seems a little unnatural.... あげる Also means she's doing it, not the player, though I can see why you went with the translation that you did. In English お姉さん doesn't have to directly be translated to "big sis" since it's a little unnatural.

"Now; there's somewhere I'd like to take you OK? I'll give you a proper "thank you"/"reward" in the waiting room that'll make you feel good."

2024-10-04 23:43 UTC, Giratena commented on CSV/Language/English/Card/70024.txt
> +あ～、{主人公}くん、来てくれたんだ～❤\nわたしがお礼してあげるって言ったの覚えてる？\nいま時間があれば、ちょうど暇だし、してあげるよ～❤,Ah~;{主人公}. You came to see me.❤ Did you remember how I promised to give you a reward? I'm free right now; so I can give it to y
I'm not sure if "reward" is the right word for this translation here, though I could be wrong. Is she rewarding him or thanking him?

2024-10-04 23:43 UTC, Giratena commented on CSV/Language/English/Card/70024.txt
> +(うう、僕は何をやっているのだろうか。\n闘技場で試合を申し込むはずだったのに、\n女の人にパイズリなんてされて・・・❤),(Uuh... What on earth am I doing? I meant to register for a match; but now I'm having a girl give me a boobjob...)
"**Gah...** What on earth am I doing? I was meant to register for a match; but **now this girl is giving me** a boobjob...)

2024-10-04 23:43 UTC, Giratena commented on CSV/Language/English/Card/70024.txt
> +(こんなことしていないで、\n少しでも強くならないといけないのに・・・❤\nはひぃ、きもちいい・・・❤),(This isn't what I should be doing. I should resist...❤ Aah... But it feels so good...❤)
(I **shouldn't be doing this. I have to resist**...❤ But **a-ah... It** feels so good...❤)

2024-10-04 23:43 UTC, Giratena commented on CSV/Language/English/Card/70024.txt
> +わたしの重たいおっぱいに潰してもらえるの、気持ちいいでしょ～❤\n柔らかくて隙間ができないから、\nおちんちんにぴったり密着してくるんだよ❤,It feels amazing to get crushed between my soft and heavy boobs; right? They're perfectly latching around your dick without a si
The feeling of being crushed between my soft and heavy boobs is amazing; right? They're perfectly **enveloping your dick** without a single gap.❤

2024-10-04 23:43 UTC, Giratena commented on CSV/Language/English/Card/70024.txt
> +魔力を吸い取る量を少なめにしてくれていたらしく、そのあと体は回復したが、やわらかいおっぱいの感触は僕の記憶に深く刻み込まれたのだった。,Shortly after that-likely because she hadn't taken much of my mana-I could feel the strength finally return to my body. However; wh
Use — instead of - for this kind of gramatical convention.

2024-10-04 23:43 UTC, Giratena commented on CSV/Language/English/Card/70024.txt
> +わたしの谷間の、一番奥まで届くかな～❤\nほら、ぎゅっ、ぎゅっ、ぎゅ～❤❤\n白いのどぴゅって出しちゃえ～❤,I wonder if your load can reach the deepest parts of my boobs?❤ C'mon; I'll squeeze your dick even tighter; so shoot out your white juices.❤
I wonder if your load **will** reach the deepest parts of my boobs

2024-10-04 23:43 UTC, Giratena commented on CSV/Language/English/Card/70024.txt
> +くすくす❤そんなに何回も迷うぐらいなら、\nほら、わたしと気持ちいいことしよう？,Ehehe.❤ Isn't it about time you let me make you feel good when you keep hesitating about it so much?
"Isn't it time you let me make you feel good? There's no need to keep hesitating about it so much."

2024-10-04 23:43 UTC, Giratena commented on CSV/Language/English/Card/70024.txt
> +ん～、{主人公}くん、どうしたの？\nあ、やっぱり今日「お礼」してほしくなっちゃった？,Hmmm? {主人公}; what's up? Ah! Do you feel like accepting the "reward" now?
the -> my

2024-10-04 23:43 UTC, Giratena commented on CSV/Language/English/Card/70024.txt
> +まあいいや。もししてほしくなったら、\nわたしに声をかけてね。このおっぱいでたくさん\n気持ちいい「お礼」をしてあげるから。うふふ❤,Well; fine. But if you change your mind; just say the word; and I'll give you the "reward" with my boobs. Ehehe.❤
the "reward" -> my/a "reward"

2024-10-04 23:43 UTC, Giratena commented on CSV/Language/English/Card/70024.txt
> +バトルじゃないときにカードマスターにエッチなことしてもらえるの、\n腰が抜けちゃうぐらいすごいでしょ❤\nバリアなしのパイズリとかされると、癖になっちゃう人も多いんだって。,Having a cardmaster do naughty things to you outside of a duel feel so good that it makes your legs get weak; ri
I've heard that a lot of people have actually got addicted to boobjobs and such when this kind of stuff **was done to them without their magic barrier protecting them.**

2024-10-11 08:49 UTC, PummelsTL commented on CSV/Language/English/Card/70024.txt
> +(うう、僕は何をやっているのだろうか。\n闘技場で試合を申し込むはずだったのに、\n女の人にパイズリなんてされて・・・❤),(Uuh... What on earth am I doing? I meant to register for a match; but now I'm having a girl give me a boobjob...)
Changed to:
(Gah... What on earth am I doing? I meant to register for a match; but now I'm getting a boobjob from this girl...)

2024-10-11 09:02 UTC, PummelsTL commented on CSV/Language/English/Card/70024.txt
> +あ～、{主人公}くん、来てくれたんだ～❤\nわたしがお礼してあげるって言ったの覚えてる？\nいま時間があれば、ちょうど暇だし、してあげるよ～❤,Ah~;{主人公}. You came to see me.❤ Did you remember how I promised to give you a reward? I'm free right now; so I can give it to y
You can do it either way. She's thanking/rewarding you as the "guardian" of West Town for taking out the bandits. I added the translation of the context for this (lines 23-25).
Although, by using the word reward, you could probably drop all the quotation marks she uses around the word.

2024-10-22 09:07 UTC, Giratena commented on CSV/Language/English/Card/70024.txt
> +あ～、{主人公}くん、来てくれたんだ～❤\nわたしがお礼してあげるって言ったの覚えてる？\nいま時間があれば、ちょうど暇だし、してあげるよ～❤,Ah~;{主人公}. You came to see me.❤ Did you remember how I promised to give you a reward? I'm free right now; so I can give it to y
Sounds good to me then ^^

2024-10-22 09:07 UTC, merged

2024-10-22 09:07 UTC, Giratena commented
Merged in! Nice work @PummelsTL ^^