Proofread taiga
Giratena/Succubus-Duel-English-Translation pull request #215
Opened 2024-12-23 01:29 UTC by HotHeadEmperor

2024-12-30 07:24 UTC, Giratena requested changes
Nice work Hothead! Just one small change from me.

2024-12-30 07:24 UTC, Giratena commented on CSV/Language/English/Card/70005.txt
> +Fランクの獣人の少年。獣タイプのモンスターを中心にしたデッキを使用する。まだカードを使い始めたばかりで、あまり強いモンスターを扱うことができない。Cランクの姉にカードの使い方を教わって、日々修行中である。,A young foxkin F-rank cardmaster who's deck specializes in beast-type monsters. He's just starti
Good spot here!

2024-12-30 07:24 UTC, Giratena commented on CSV/Language/English/Card/70005.txt
> +ボクはタイガ。ギルドに入って3ヵ月のF級カードマスターだ！,My name's Taiga. I'm an F-rank cardmaster; and I've been in the guild for three months!
Both are correct here but I like the flow of what you've added ^^

2024-12-30 07:24 UTC, Giratena commented on CSV/Language/English/Card/70005.txt
> +ボクの攻撃！{防御カード}を攻撃！,My turn to attack! Go; {防御カード}!
{防御カード} is actually the target of the attack. Taiga is declaring his attack against an enemy character, so you'll want to either change or revert this ^^

- [ ] Change this one line.

2024-12-30 23:51 UTC, HotHeadEmperor commented on CSV/Language/English/Card/70005.txt
> +ボクの攻撃！{防御カード}を攻撃！,My turn to attack! Go; {防御カード}!
Small change. See how that looks, and if you don't like it, I'll just revert it and see how it flows in play.

2024-12-31 23:53 UTC, Giratena commented on CSV/Language/English/Card/70005.txt
> +ボクの攻撃！{防御カード}を攻撃！,My turn to attack! Go; {防御カード}!
Hmm... "I'll fight" seems a little too on the nose. Let's revert ^^

2025-01-07 09:43 UTC, Giratena approved these changes

2025-01-07 09:43 UTC, merged