Flare(70009)(WIP)
Giratena/Succubus-Duel-English-Translation pull request #45
Opened 2024-05-04 18:29 UTC by PummelsTL

2024-07-29 23:28 UTC, Giratena requested changes
Translation looks good from a once over Pummels! Nice work ^^

Just a quick heads up for this and future PRs to keep in mind the punctuation around hearts:

> Any ❤, must be prefixed with puncuation. Eg: ".❤", "!❤", "?❤", "~❤", or "...❤"

This is something that I think should be consistent across the translation so I'd like to really push for it. Feel free to do a global find and replace for it if you need to ^^

2024-07-30 11:40 UTC, PummelsTL commented
Added punctuation for the hearts.

2024-08-05 08:00 UTC, Giratena requested changes
Not bad @PummelsTL! Good accurate translations for the most part. Nice work!

I had a look and noticed some things with formatting. Please take a look!

I also noticed there appears to be a lack of attention towards laughing sfx, choosing to translate them all as a blunt "Ahaha." I've pointed these out for you to have a look at. I hope it helps. 

I know it might seem trivial, but it can potenitally muddle the intended voice of a Japanese character if not done correctly.

Hope this review helps :D

2024-08-07 12:06 UTC, PummelsTL commented on CSV/Language/English/Card/70009.txt
> +あっは❤ばかにされてしごくスピード速くなってるし❤男にとってはそんなに我慢できないものなのかな、おっきいおっぱいって❤,Ahaha❤ Your hand sped up when I made fun of you.❤ Do men find huge breasts like mine just that irresistible?
Fixed.

2024-08-07 12:07 UTC, PummelsTL commented on CSV/Language/English/Card/70009.txt
> +それなら、こうしちゃえばいいのよ❤,But the inefficiency shouldn't a problem if I do this.❤
I agree.

2024-08-07 12:09 UTC, PummelsTL commented on CSV/Language/English/Card/70009.txt
> +う～ん おいしい❤やっぱり、アンタって\n良質な魔力を持ってるみたい❤もっともっと搾りとってあげるから、\nわたしにぜんぶ捧げちゃいなさい❤,Mmmh... Delicious.❤ You've got some fine-quality mana❤ I'll keep draining you for more; so make sure to offer it all to me.❤
I agree. Added suggestions.

2024-08-07 12:11 UTC, PummelsTL commented on CSV/Language/English/Card/70009.txt
> +はい、イっちゃった❤\nね？一回チンポ挟んじゃえば、\nうぶな男の子なんて何回でも連続射精させられるわ❤,There it is.❤ You know? It's a trifling thing for me to make naive boys like you cum several times in a row once I have your penis between my brea
Changed to: "And there: You spilled your load.❤ Did you know?"

2024-08-07 12:14 UTC, PummelsTL commented on CSV/Language/English/Card/70009.txt
> +ふふ、出た出た❤\nチンポをおっぱいで捕まえちゃえば、男なんてわたしの思うままよ❤,Ahaha. There it is.❤ Men have no choice but to do as I say once I have their penis trapped between my breasts.❤
Changed to "Ahaha! You blew your load.❤"

2024-08-07 12:15 UTC, PummelsTL commented on CSV/Language/English/Card/70009.txt
> +こんな風に罵られてもうっとりした顔のままだし、重症だわ❤\n何もできないでくの坊のにはさっさと退場願うとしましょう。\nくすくす❤,And you're even watching me with enraptured eyes even though I'm making fun of you.❤ You've got some serious issues.❤ Idiots who can'
I chose to remove this laugh at the end altogether.

2024-08-07 12:17 UTC, PummelsTL commented on CSV/Language/English/Card/70009.txt
> +おっぱいをズリズリ動かして、\n足腰立たなくなるまで気持ちよくしてあげる❤\n覚悟しなさい。ふふふ❤,Now; I'll start moving and make you feel so good that your legs give in.❤ Get ready for it. Ahahaha.❤
I think this is fine as is.

2024-08-08 23:09 UTC, Giratena requested changes
One major change here and I think that's it.

I still notice the translations of simply "Ahaha." do take away from some of the varied Japanese laughs. I'd have a look at those again if you have a change. After your next changes I'll merge ^^

2024-08-08 23:09 UTC, Giratena commented on CSV/Language/English/Card/70009.txt
> +あーあー、わたしに促されるままイっちゃって❤気持ちよかったかしら？うふふ❤,Aa-ah. You blew your semen just as I told you to.❤ Did it feel good? Ahaha.❤
Ah-ah → Oh dear,
Ahaha -> Ufufu or *giggle*

I think あーあー has more of a condesending vibe than just a laugh.

2024-08-08 23:09 UTC, Giratena commented on CSV/Language/English/Card/70009.txt
> +うふふ、君たちっていつもそうね❤立派な剣術や拳、魔法を持っているのに、敵の女の子がえっちだとすぐに惑わされちゃう❤,Ahaha. This is how it's for all you men.❤ Even if you're skilled with swords; fists; or magic; you can't help but get charmed the moment you
Ufufu here or Ehehe etc

2024-08-08 23:09 UTC, Giratena commented on CSV/Language/English/Card/70009.txt
> +あーあー、自分でしこって出しちゃった❤ね、わたしの体がそんなにえっちだったの？うふふ❤,Aa-ah. You really went and stroked yourself all the way.❤ Was my body that irresistibly sexy? Ahahaha.❤
Same as line 138

2024-08-13 08:50 UTC, PummelsTL commented on CSV/Language/English/Card/70009.txt
> +あーあー、わたしに促されるままイっちゃって❤気持ちよかったかしら？うふふ❤,Aa-ah. You blew your semen just as I told you to.❤ Did it feel good? Ahaha.❤
There is no "Ah-ah" laugh here but an "Aa-ah" sound that carries a condescending tone.
I can't see changing the laugh changing anything.

2024-08-13 09:14 UTC, Giratena commented on CSV/Language/English/Card/70009.txt
> +やったぁ！上のランク相手でも勝てた！\nわたしの炎デッキの力、すごいでしょ！,Yay! I won against a higher-rank opponent! My flame deck is amazing!
I think "Fire" deck might be a better name, for "Fire Attribute" etc

2024-08-13 09:15 UTC, Giratena commented on CSV/Language/English/Card/70009.txt
> +またいつでも再戦待ってるわね！,You can for a rematch anytime!
-> Feel free to rematch again anytime!

2024-08-13 09:16 UTC, PummelsTL commented on CSV/Language/English/Card/70009.txt
> +あーあー、わたしに促されるままイっちゃって❤気持ちよかったかしら？うふふ❤,Aa-ah. You blew your semen just as I told you to.❤ Did it feel good? Ahaha.❤
あーあー -> Now; look at this.

2024-08-13 09:17 UTC, PummelsTL commented on CSV/Language/English/Card/70009.txt
> +あーあー、自分でしこって出しちゃった❤ね、わたしの体がそんなにえっちだったの？うふふ❤,Aa-ah. You really went and stroked yourself all the way.❤ Was my body that irresistibly sexy? Ahahaha.❤
Aa-ah. -> Now; look at you.

2024-08-13 09:27 UTC, PummelsTL commented on CSV/Language/English/Card/70009.txt
> +またいつでも再戦待ってるわね！,You can for a rematch anytime!
-> You can ask me for a rematch anytime!

2024-08-13 09:27 UTC, PummelsTL commented on CSV/Language/English/Card/70009.txt
> +やったぁ！上のランク相手でも勝てた！\nわたしの炎デッキの力、すごいでしょ！,Yay! I won against a higher-rank opponent! My flame deck is amazing!
Changed instances of flame to fire/fire-attribute.

2024-08-15 22:12 UTC, Giratena approved these changes
Nice work! Will approve and merge ^^
Thank you very much @PummelsTL!

2024-08-15 22:12 UTC, merged