Update 1 10002.txt
Giratena/Succubus-Duel-English-Translation pull request #47
Opened 2024-05-08 14:20 UTC by 1BadGloop

First attempt at a partial translation of the Samurai Girl's lines. Translates the first 20 lines or so.

Please let me know if I've translated correctly enough and formatted the lines properly! I have little to no experience with GitHub and VSCode so I'm learning as I go!

2024-05-08 16:00 UTC, 1BadGloop commented
Made some changes to formatting mistakes that I found in my edits.

2024-05-13 10:11 UTC, OfficialLayton requested changes
Very nice first PR @1BadGloop!

I had a read through and made some comments ^^

- Keep in mind punctuation, especially around ❤
- The tone of the character is that they are speaking prim and proper, and in old styled fashion. It appears there has been some effort into this from reading so nice job!
- Remember to faithfully translate sfxs into English. What is there is quite good but just some things that weren't caught
- You appear to have removed all the \n markings! Please keep these in mind since they are needed. When in doubt just use the same formatting as the Japanese text.
- Just double checking translations to make sure they're accurate.

Hope this helps! Looking forward to seeing the cleaning up version. Nice work :D

2024-05-13 10:11 UTC, OfficialLayton commented on CSV/Language/English/Card/10002.txt
> +シコシコ、シコシコ❤そんなに気持ちいいのかのう？,Shiko; shiko; shiko; shiko❤Does it really feel that good?
Instead of saying Shiko- which is the Japanese sound effect for stroking- It should be replaced with the English equivilant instead!

So this could be somthing like, "stroke stroke, pump pump~". As an example.

2024-05-13 10:11 UTC, OfficialLayton commented on CSV/Language/English/Card/10002.txt
> +拙者の指使いはどうでござるか？いちもつをそっと握って、\nしこしこ、しこしこ❤しこしこ、しこしこ❤\n頭まっしろにして、そのまま負けていいでござるよ❤,How's my handjob? Gently grasping your wood and rubbing it...Lose.❤Lose.❤Lose.❤ Go ahead and cum.❤ Virgin Master.❤
I really like the extention here! Sometimes writing more words in place of Japanese sound effects is the best translation you can give. Nice job on that ^^

Though, I'd warn against going to far though. She doesn't repeatedly say lose here which is quite a change in meaning so perhaps dropping that would be better.

Also, it seems that " Virgin Master.❤" appears here even though it's not in the Japanese text.

2024-05-13 10:11 UTC, OfficialLayton commented on CSV/Language/English/Card/10002.txt
> +ほら、拙者が天国に行く手伝いをしてやるでござる。\n両手で筒を作って、しこしこ❤しこしこ❤,I shall make you feel as though you're in heaven. I shall make a tube with both hands and squish.❤ squish.❤ squish❤
Remember to have capital letters for the "squish"s that are after the full stop.

2024-05-13 10:11 UTC, OfficialLayton commented on CSV/Language/English/Card/10002.txt
> +マスターのことなど忘れさせてやるでござる。\n拙者のパイズリでたっぷり気持ちよくなれ❤ククク❤,I will make you forget about Master; that I will. You will feel good with my titjob.❤kukkuk.❤
Capital letter and spacing

2024-05-13 10:11 UTC, OfficialLayton commented on CSV/Language/English/Card/10002.txt
> +拙者の手さばきで果てたいと申すか❤\nくすくす❤そこまで大きな声で頼まれれば悪い気はせぬでござる❤\n腰が抜けるほどしごいてやるでござるよ❤,You want to cum from my handjob?❤Giggle.❤ You must not have any issue with that; asking that loudly.❤  I shall squeeze it until
Space here

2024-05-13 10:11 UTC, OfficialLayton commented on CSV/Language/English/Card/10002.txt
> +おぬしのイチモツを優しく指で包んで、しこしこ…❤しこしこ…❤,I shall gently wrap my fingers around your penis and rub it...❤ rub.❤ rub.❤ rub.❤
Capital letters on Rub here.

2024-05-13 10:11 UTC, OfficialLayton commented on CSV/Language/English/Card/10002.txt
> +手でしごかれるのは好きでござるか？,You like it when I squeeze it with my hands; don't you?
Spacing

2024-06-26 06:50 UTC, merged