Update 70006.txt
Giratena/Succubus-Duel-English-Translation pull request #56
Opened 2024-06-15 18:10 UTC by Kyrari

Translated Eruru (Town) event scene
There's an MC choice dialogue missing here though.

2024-08-02 09:14 UTC, Kyrari commented on CSV/Language/English/Card/70006.txt
> +あなたのランクはF級？ふーん、まだカードを始めたばっかりなんだ。,You're an F-rank, is it? Hmm; so you're just starting out.
Ah, true. I forgot to recheck and missed some , on line 9 85 113 114... fixed now and reworded.

2024-08-02 09:14 UTC, Kyrari commented on CSV/Language/English/Card/70006.txt
> +くすくす❤\nバトルの途中なのに、敵のマスターにおねだりしちゃうんだ❤\n初心者マスターのモンスターだけあって、理性が弱いのね❤,*giggle*❤ Even though we're in the middle of a battle; to beg your opponent❤ Even if you're the monster of a beginner master; your sel
Ah, yeah I forgot about heart punctuations. Should be fixed now.

2024-08-02 09:15 UTC, Kyrari commented on CSV/Language/English/Card/70006.txt
> +わたしのターンはおわり。ターンエンド。,I end my turn. Turn end.
Yeah, that does sound strange. Changed

2024-08-05 08:45 UTC, Kyrari commented
Accidentally added the 70014 on this PR so I'll just work on it here too and change the PR name...

2024-08-08 04:16 UTC, Giratena commented
Friendly reminder to resolve the merge conflicts @Kyrari ^^
Otherwise nice work! WIll take a bit to look through everything fully but at a glace looks good!

2024-08-08 04:17 UTC, Giratena requested changes
To resolve merge conflicts ^^

2024-08-11 11:29 UTC, Giratena requested changes
Salutations @Kyrari!
I've Just a bit of a mid review and had a look through your translations ^^

I've had a bit of a look through and left some comments! Hopefully you find them helpful ^^

Most of the translations hit the mark, but some are also just a *tad* bit off in either translation meaning or English nuance! I'd reccomend looking through and fixing anything you can before I look through again.

Looking forward to see your translations improve, and keep up the good work! :D

2024-08-11 11:29 UTC, Giratena commented on CSV/Language/English/Card/70006.txt
> +それなら、そのままじっとしててよ…❤んっちゅ❤,Then just keep watching me like that...❤ Smooch~❤
それなら、doesn't just mean "then", it more so means "that being the case..." (related to the listener wanting to do things that feel good with her)

Then just keep watching me like that...❤ Smooch\~❤-> If you do; then just keep staying still...❤ Smooch~❤

2024-08-11 11:29 UTC, Giratena commented on CSV/Language/English/Card/70006.txt
> +投げキッスで興奮させたげる。んっちゅ❤,I'll make you get excited from blown kisses. Smooch~❤
"get excited" sounds a bit unnatural in English. Maybe translate it like:
I'll make you get excited from blown kisses. Smooch~❤->
I'll arouse you with my blown kisses. Smooch\~❤

2024-08-11 11:29 UTC, Giratena commented on CSV/Language/English/Card/70006.txt
> +手でいじめてあげる。ほら、ぎゅってチンコを握って、シコシコ…❤,I'll tease you with my hands. Here; I'll squeeze it. Rub; rub...❤
Make sure to keep to the translation to the word if you can help it. You'll want to capture a better translation of "ぎゅってチンコを握って"
You can also nuance and localize シコシコ…❤ since it'll flow more naturally. Somethinng like:

手でいじめてあげる。ほら、ぎゅってチンコを握って、シコシコ…❤ -> I'll tease your dick with my hands. Look; by holding it tightly; I can start stroking it up and down...❤

2024-08-11 11:29 UTC, Giratena commented on CSV/Language/English/Card/70006.txt
> +意外と優しい扱き方でしょ？頭のなかとろとろにしちゃうね。ふふふ❤,It's surprisingly gentle; isn't it? I'll make your head turn into a mess; hehe~❤
What's "it" in this situation? Remember to translate "扱き方" -> "method of stroking"
Also the "しちゃう" does not mean "I'll do" it means "to unexpectly finish or happen".

So this sentence is more like: 
意外と優しい扱き方でしょ？頭のなかとろとろにしちゃうね。ふふふ❤ -> The way I stroke has a certain gentleness to it; right? I bet it's making your mind go all fuzzy. Teehee.❤

2024-08-11 11:29 UTC, Giratena commented on CSV/Language/English/Card/70006.txt
> +はい、わたしの勝ち。やっぱりF級とD級じゃ、実力が違うわよね。クスクス。,Yep; it's my win. There really is a big gap between F-rank and D-rank; *giggle*
"Yep; it's my win." sounds pretty unnatural.

はい、わたしの勝ち。やっぱりF級とD級じゃ、実力が違うわよね。クスクス。-> Right. Looks like I win. There really is a big gap between F-rank and D-rank huh? *Giggle*

2024-08-11 11:29 UTC, Giratena commented on CSV/Language/English/Card/70006.txt
> +はい、わたしの勝ち。やっぱりE級とD級じゃ、実力が違うわよね。クスクス。,Yep; it's my win. There really is a big gap between E-rank and D-rank; *giggle*
Same as line 25.

2024-08-11 11:29 UTC, Giratena commented on CSV/Language/English/Card/70006.txt
> +うっ、さすがね。やるじゃない、{主人公}。\nでも次は勝つわ。またバトルしましょう。,Ugh; I thought so. You're not half bad; {主人公}. But I'll win the next time we have a battle.
しましょう means "Let's do" in an inclusive way.
So, she's actually saying:

うっ、さすがね。やるじゃない、{主人公}。\nでも次は勝つわ。またバトルしましょう。-> "Ugh; as I suspected. You're not half bad; {主人公}. But next time; victory will be mine. Let's battle again sometime; OK?

2024-08-11 11:29 UTC, Giratena commented on CSV/Language/English/Card/70006.txt
> +わたしのターンからね。いくわよ、わたしの闇属性モンスターでこてんぱんにしてあげる。,It's my turn. My Dark Attribute monster will beat you thoroughly.
Dark Attribute monster -> dark attribute monster 
Also maybe do a search in the file for this change ^^

2024-08-11 11:29 UTC, Giratena commented on CSV/Language/English/Card/70006.txt
> +あなたのこと気持ちよくしてあげるわね。{防御カード}を攻撃！,I'll make you feel good. Attack {防御カード}!
Make sure to capture the nuance of "わね". It might be a small change but still an oppertunity to bring personality to a character in English ^^
EG: "I'll make you feel good now~ Attack {防御カード}!"

2024-08-14 08:40 UTC, Kyrari commented on CSV/Language/English/Card/70006.txt
> +あなたのこと気持ちよくしてあげるわね。{防御カード}を攻撃！,I'll make you feel good. Attack {防御カード}!
changed, I originally had most of ね ends into ~ but must've missed this

2024-08-14 08:40 UTC, Kyrari commented on CSV/Language/English/Card/70006.txt
> +はい、わたしの勝ち。やっぱりE級とD級じゃ、実力が違うわよね。クスクス。,Yep; it's my win. There really is a big gap between E-rank and D-rank; *giggle*
sure, changed wording

2024-08-14 08:41 UTC, Kyrari commented on CSV/Language/English/Card/70006.txt
> +はい、わたしの勝ち。やっぱりF級とD級じゃ、実力が違うわよね。クスクス。,Yep; it's my win. There really is a big gap between F-rank and D-rank; *giggle*
sure, changed wording

2024-08-14 08:41 UTC, Kyrari commented on CSV/Language/English/Card/70006.txt
> +手でいじめてあげる。ほら、ぎゅってチンコを握って、シコシコ…❤,I'll tease you with my hands. Here; I'll squeeze it. Rub; rub...❤
true, changed

2024-08-14 08:41 UTC, Kyrari commented on CSV/Language/English/Card/70006.txt
> +投げキッスで興奮させたげる。んっちゅ❤,I'll make you get excited from blown kisses. Smooch~❤
I'll arouse you doesn't feel right to me, but yea I can change to the 1st suggestion

2024-08-14 08:41 UTC, Kyrari commented on CSV/Language/English/Card/70006.txt
> +それなら、そのままじっとしててよ…❤んっちゅ❤,Then just keep watching me like that...❤ Smooch~❤
I'm pretty sure 'then' does convey that meaning already, "because of event1 then event 2 happens".

I'll change to "stay still" though, I think I misread that since I automatically associated じっと with looking.

2024-08-14 08:41 UTC, Kyrari commented on CSV/Language/English/Card/70006.txt
> +ねえほら、唇を見て？\n{主人公}はわたしと気持ちいいことしたい？,Hey; are you looking at my lips? {主人公} wants me to do pleasurable things; don't you?
true, changed

2024-08-14 08:41 UTC, Kyrari commented on CSV/Language/English/Card/70006.txt
> +F級カードマスターくんはまだまだ女の子に対してうぶなんでしょ？\nわたしと気持ちいいことしたい？,Mr. F-rank is still naive about girls; aren't you? Don't you want to do something good with me?
sure, changed

2024-08-14 08:41 UTC, Kyrari commented on CSV/Language/English/Card/70006.txt
> +E級カードマスターくんはまだまだ女の子に対してうぶなんでしょ？\nわたしと気持ちいいことしたい？,Mr. E-rank is still naive about girls; aren't you? Don't you want to do something good with me?
sure, changed

2024-08-14 08:41 UTC, Kyrari commented on CSV/Language/English/Card/70006.txt
> +やっほー。F級カードマスターくん。また会ったわね。バトルする？,Yahoo~; Mr. F-rank. We meet again; wanna have a battle?
sure, changed

2024-08-14 08:41 UTC, Kyrari commented on CSV/Language/English/Card/70006.txt
> +この間わたしが負けたのは運よ。運。今度は勝つわ。さあ行くわよ！,It was just bad luck that I lost last time; bad luck. This time I'll definitely win. Come at me!
sure, changed

2024-08-14 08:42 UTC, Kyrari commented on CSV/Language/English/Card/70006.txt
> +やっほー。{ランク名}級カードマスターくん。また会ったわね。バトルする？,Yahoo~; Mr. {ランク名}-rank. We meet again; wanna have a battle?
Eh, I think it works in an informal setting (or I should've used yoohoo variant) but sure can just change to this.

I'll just remove every Mr. from the rest of the text

2024-08-15 22:33 UTC, Giratena requested changes
Just some small changes again sorry!
These are small ones though so I think I'll just resolve them myself to save you time. ^^

Nice work!

2024-08-15 22:33 UTC, Giratena commented on CSV/Language/English/Card/70006.txt
> +おっぱいあったかくて気持ちいい？そのまま力抜いてなさい。\nきっと耐えられなくて、すぐに終わるわ。\nよいしょっ。ズリズリ、ズリズリ…❤,Is my breasts that good? Just relax yourself like that. I'm sure you wouldn't be able to resist this; so this'll be over soon. Squ
Is my breasts that good? -> "Do my breasts feel that good?"

2024-08-15 22:33 UTC, Giratena commented on CSV/Language/English/Card/70006.txt
> +女の子の手って柔らかいから気持ちいいのよ。ほら、実際にやったげる。シコシコ、シコシコ…♪,A girl's soft hands will feel really good. Here; I'll do it for you. Jerk; jerk...♪
Jerk; jerk...♪ -> Stroke stroke; stroke stroke...♪

2024-08-15 22:33 UTC, Giratena commented on CSV/Language/English/Card/70006.txt
> +そこで勃起チンポ抱えてじっとしてれば？\nすぐにまたエナジーを搾り取ってあげる❤\nま、ほかのモンスターにぼこられちゃうかもだけど❤,How about you just stay still and hold that erection out? I'll squeeze your energy again real soon.❤ Well; the other monsters might
"hold that erection out" sounds a bit unnatural. Note the ば at the end is conditional!
So the sentence is more like: "And if you stay still right there with that erect dick; I'll milk your energy out right away just like last time.❤"

2024-08-15 22:33 UTC, Giratena commented on CSV/Language/English/Card/70006.txt
> +このおっぱいにチンコ入れたいなぁとか妄想しちゃってるの？\n谷間にチンコ突き入れて、そのまま両側から\nおっぱいでむにゅーって押しつぶされて…❤,Are you fantasizing about your dick entering my boobs? Just imagine it entering my cleavages; getting squeezed from both sides
Sentence is really well written here! Just one change:
entering my cleavages -> entering my cleavage

2024-08-15 22:33 UTC, Giratena commented on CSV/Language/English/Card/70014.txt
> +これはね、わたしが水の魔法で作った特別なローション❤\nちょっとエッチな成分も混ぜてあるの❤,This here is a special lotion made using my water magic.❤ I also mixed some lewd ingredients to it.❤
to it -> in it

2024-08-15 22:39 UTC, Giratena approved these changes
Hi @Kyrari! I've gone through and fixed the minor typos I spotted myself. Will merge this in now ^^

2024-08-15 22:39 UTC, merged